# Generated by Django 5.2 on 2025-05-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_alter_simulation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='strategy',
            field=models.CharField(choices=[('DCA', 'Dollar Cost Averaging'), ('LUMP', 'Lump Sum')], max_length=10),
        ),
    ]
