# Generated by Django 5.2 on 2025-05-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_simulation_profit_alter_simulation_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='total_shares',
            field=models.FloatField(default=0.0),
        ),
    ]
